# Generated by Django 3.2.19 on 2024-11-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clockify_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
