# Generated by Django 3.2.19 on 2024-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_project_clockify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clockify_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
