# Generated by Django 3.2.19 on 2025-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_alter_project_clockify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tracking_mode',
            field=models.CharField(choices=[('project', 'Track by Project'), ('epic', 'Track by Epic')], default='project', max_length=10, verbose_name='tracking mode'),
        ),
    ]
