# Generated by Django 3.2.19 on 2026-07-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_project_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_changelog_activated',
            field=models.BooleanField(blank=True, default=False, verbose_name='active changelog panel'),
        ),
    ]
