# Generated by Django 3.2.19 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_project_is_changelog_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='is_changelog_activated',
            field=models.BooleanField(blank=True, default=False, verbose_name='active changelog panel'),
        ),
    ]
