# Generated by Django 3.2.19 on 2026-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_project_webhook_status_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clockify_id',
        ),
        migrations.AddField(
            model_name='project',
            name='kimai_project_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kimai project id'),
        ),
    ]
