# Generated by Django 3.2.19 on 2025-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0006_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='clockify_project_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='clockify project id'),
        ),
    ]
