# Generated by Django 3.2.19 on 2026-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0007_epic_clockify_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='clockify_project_id',
        ),
        migrations.AddField(
            model_name='epic',
            name='kimai_project_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kimai project id'),
        ),
    ]
