# Generated by Django 3.2.19 on 2024-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20211110_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clockify_key',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
