# Generated by Django 3.2.19 on 2024-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20211110_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clockify_key',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='clockify key'),
        ),
    ]
