# Generated by Django 3.2.19 on 2024-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_clockify_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clockify_key',
            field=models.CharField(max_length=48, null=True, unique=True),
        ),
    ]
