# Generated by Django 3.2.19 on 2024-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_user_clockify_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clockify_id',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
