# Generated by Django 3.2.19 on 2026-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_clockify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clockify_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clockify_key',
        ),
        migrations.AddField(
            model_name='user',
            name='kimai_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kimai api token'),
        ),
    ]
