# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos INC

# Generated by Django 2.2.14 on 2020-12-02 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryPullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_url', models.URLField(unique=True, verbose_name='pull request URL')),
                ('branch_name', models.TextField(verbose_name='branch name')),
                ('pull_request_id', models.BigIntegerField(blank=True, null=True, verbose_name='pull request ID')),
                ('repository', models.TextField(blank=True, null=True, verbose_name='repository')),
                ('merged_by', models.TextField(blank=True, null=True, verbose_name='merged by')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='merged at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='userstories.UserStory', verbose_name='user story')),
            ],
            options={
                'verbose_name': 'user story pull request',
                'verbose_name_plural': 'user story pull requests',
                'ordering': ['user_story', '-merged_at'],
            },
        ),
    ]
