# Generated by Django 3.2.19 on 2026-07-23 17:26

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0071_project_is_changelog_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='GitHub repository, e.g. "my-org/my-repo"', verbose_name='repository full name')),
                ('branches', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='branches of interest')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_repositories', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'changelog repository',
                'verbose_name_plural': 'changelog repositories',
                'ordering': ['project', 'full_name'],
                'unique_together': {('project', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.TextField(verbose_name='branch')),
                ('compare_url', models.URLField(verbose_name='compare URL')),
                ('before_sha', models.CharField(blank=True, max_length=64, null=True, verbose_name='before commit sha')),
                ('after_sha', models.CharField(max_length=64, verbose_name='after (head) commit sha')),
                ('head_message', models.TextField(blank=True, null=True, verbose_name='head commit message')),
                ('pusher_name', models.TextField(blank=True, null=True, verbose_name='pusher name')),
                ('commits', taiga.base.db.models.fields.json.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of {message, author_name, url}, merge commits excluded', verbose_name='commits')),
                ('delivery_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='GitHub delivery id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='changelog.changelogrepository', verbose_name='repository')),
            ],
            options={
                'verbose_name': 'changelog entry',
                'verbose_name_plural': 'changelog entries',
                'ordering': ['-created_date'],
                'unique_together': {('repository', 'after_sha')},
            },
        ),
    ]
