# Generated by Django 3.2.19 on 2026-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_project_webhook_status_map'),
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogrepository',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=20, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='changelogrepository',
            name='full_name',
            field=models.TextField(help_text='Repository, e.g. "my-org/my-repo"', verbose_name='repository full name'),
        ),
        migrations.AlterUniqueTogether(
            name='changelogrepository',
            unique_together={('project', 'platform', 'full_name')},
        ),
    ]
